
[[enumerations]]
== Enumerations and bitfields

An *enumeration* is a string (a literal) from a well defined set of values.

A *bitfield* represents a set of or'd flags. When used as a function argument it may be passed either as an integer code, or as a sequence of strings from a well defined set of values. When it is not the last argument of the function, it may be passed only as an integer code. Functions returning a *bitfield* return the integer code only (utilities are provided to <<additional, encode/decode bitfields>>, if needed).


[[bboxmode]]
* *bboxmode*: enumeration. +
[small]#Values: '_unscaled_', '_gridfit_', '_truncate_', '_pixels_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Glyph_BBox_Mode++[FT_Glyph_BBox_Mode].#

[[border]] 
* *border*: enumeration. +
[small]#Values: '_left_', '_right_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_stroker.html#FT_StrokerBorder++[FT_StrokerBorder].#


[[encoding]] 
* *encoding*: enumeration. +
[small]#Values: '_none_', '_ms symbol_', '_unicode_', '_sjis_', '_gb2312_', '_big5_', '_wansung_', '_johab_', '_adobe standard_', '_adobe expert_', '_adobe custom_', '_adobe latin 1_', '_apple roman_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Encoding++[FT_Encoding].#

[[fstypeflags]]
* *fstypeflags*: bitfield. +
[small]#Code: a combination of ft.FSTYPE_XXX values (corresponding to FT_FSTYPE_XXX defines). +
Strings: '_installable embedding_' (0), '_restricted license embedding_', '_preview and print embedding_', '_editable embedding_', '_no subsetting_', '_bitmap embedding only_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_FSTYPE_XXX++[FT_FSTYPE_XXX].#


[[glyphformat]] 
* *glyphformat*: enumeration. +
[small]#Values: '_none_', '_composite_', '_bitmap_', '_outline_', '_plotter_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Glyph_Format++[FT_Glyph_Format].#

[[kerningmode]] 
* *kerningmode*: enumeration. +
[small]#Values: '_default_', '_unfitted_', '_unscaled_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Kerning_Mode++[FT_Kerning_Mode].#

[[linecap]] 
* *linecap*: enumeration. +
[small]#Values: '_butt_', '_round_', '_square_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_stroker.html#FT_Stroker_LineCap++[FT_Stroker_LineCap].#

[[linejoin]] 
* *linejoin*: enumeration. +
[small]#Values: '_round_', '_bevel_', '_miter variable_', '_miter fixed_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_stroker.html#FT_Stroker_LineJoin++[FT_Stroker_LineJoin].#


[[loadflags]]
* *loadflags*: bitfield. +
[small]#Code: a combination of ft.LOAD_XXX values (corresponding to FT_LOAD_XXX defines). +
Strings: 
'_default_' (0), '_no scale_', '_no hinting_', '_render_', '_no bitmap_', '_vertical layout_', '_force autohint_', '_crop bitmap_', '_pedantic_', '_ignore global advance width_', '_no recurse_', '_ignore transform_', '_monochrome_', '_linear design_', '_no autohint_', '_color_', '_compute metrics_', '_fast only_', '_target normal_' (0), '_target light_', '_target mono_', '_target lcd_', '_target lcd v_'. +
Note: only one target flag can be included. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_LOAD_XXX++[FT_LOAD_XXX].#


[[orientation]] 
* *orientation*: enumeration. +
[small]#Values: '_fill right_' (truetype), '_fill left_' (postscript). +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html#FT_Orientation++[FT_Orientation].#


[[outlineflags]]
* *outlineflags*: bitfield. +
[small]#Code: a combination of ft.OUTLINE_XXX values (corresponding to FT_OUTLINE_XXX defines). +
Strings: '_none_', '_owner_', '_even odd fill_', '_reverse fill_', '_ignore dropouts_', '_smart dropouts_', '_include stubs_', '_high precision_', '_single pass_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html#FT_OUTLINE_XXX++[FT_OUTLINE_XXX].#


[[pixelmode]] 
* *pixelmode*: enumeration. +
[small]#Values: '_none_', '_mono_', '_gray_', '_gray2_', '_gray4_', '_lcd_', '_lcd v_', '_bgra_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Pixel_Mode++[FT_Pixel_Mode].#

[[pointtype]] 
* *pointtype*: enumeration. +
[small]#Values: '_on_', '_cubic_', or '_conic_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html#FT_Outline++[FT_Outline tags].#


[[rendermode]] 
* *rendermode*: enumeration. +
[small]#Values: '_normal_', '_light_', '_mono_', '_lcd_', '_lcd v_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Render_Mode++[FT_Render_Mode].#

[[scanmode]] 
* *scanmode*: enumeration. +
[small]#Values: '_none_', '_touch x_', '_touch y_', or '_touch both_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html#FT_Outline++[FT_Outline tags].#


[[sizerequesttype]] 
* *sizerequesttype*: enumeration. +
[small]#Values: '_bbox_', '_cell_', '_nominal_', '_real dim_', '_scales_'. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Size_Request_Type++[FT_Size_Request_Type].#


[[subglyphflags]]
* *subglyphflags*: bitfield. +
[small]#Code: a combination of ft.SUBGLYPH_FLAG_XXX values (corresponding to FT_SUBGLYPH_FLAG_XXX defines). +
Strings: 'none' (0), '_args are words_', '_args are xy values_', '_round xy to grid_', '_scale_', '_xy scale_', '_2x2_', '_use my metrics_' . +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_SUBGLYPH_FLAG_XXX++[FT_SUBGLYPH_FLAG_XXX].#


[[truetypeenginetype]] 
* *truetypeenginetype*: enumeration. +
[small]#Values: '_none_', '_patented_', '_unpatented_' +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-truetype_engine.html#FT_TrueTypeEngineType++[FT_TrueTypeEngineType].#


