
=== Glyph Management

[small]#Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#++[Glyph Management].#

* _glyph_ = *get_glyph*(<<face, _face_>>) +
[small]#Creates a glyph object. The glyph image is extracted from the current glyph slot of the given _face_. +
Also available as _face:get_glyph(&nbsp;)_ method. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Get_Glyph++[FT_Get_Glyph].#

* _newglyph_ = *glyph_copy*(_glyph_) +
[small]#Creates a glyph object copying it from another one. +
Also available as _glyph:copy(&nbsp;)_ method. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Glyph_Copy++[FT_Glyph_Copy].#

* *done_glyph*(_glyph_) +
[small]#Also available as _glyph:done(&nbsp;)_ method. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Done_Glyph++[FT_Done_Glyph].#

* <<bbox, _cbox_>> = *glyph_get_cbox*(_glyph_, <<bboxmode, _bboxmode_>>) +
[small]#Also available as _glyph:get_cbox(&nbsp;)_ method. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Glyph_Get_CBox++[FT_Glyph_Get_CBox].#

* *glyph_to_bitmap*(_glyph_, <<rendermode, _rendermode_>> [, _origin_ [, _destroy_]]) +
[small]#The _origin_ parameter is a <<vector, vector>> and defaults to _nil_ (null vector, no translation). +
The _destroy_ parameter is a boolean and defaults to _true_. +
Also available as _glyph:to_bitmap(&nbsp;)_ method. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Glyph_To_Bitmap++[FT_Glyph_To_Bitmap].#

* *glyph_transform*(_glyph_, _matrix_, _delta_) +
[small]#Also available as _glyph:transform(&nbsp;)_ method. +
The _matrix_ and _delta_ parameters are a <<matrix, matrix>> and <<vector, vector>>, respectively. +
Rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Glyph_Transform++[FT_Glyph_Transform].#

'''

The following methods are available in order to access the contents of the glyph object (see link:++https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#FT_Glyph++[FT_Glyph]):


* <<glyphformat, _glyphformat_>> = pass:[glyph]*:format*( ) +
* <<vector, _vector_>> = pass:[glyph]*:advance*( ) +
* <<bitmap, _bitmap_>> = pass:[glyph]*:bitmap*( ) +
* <<bitmapdata, _bitmapdata_>> = pass:[glyph]*:bitmapdata*( ) +
* <<outline, _outline_>> = pass:[glyph]*:outline*( ) +
* <<outlinedata, _outlinedata_>> = pass:[glyph]*:outlinedata*( ) +

