
== Structs

Most FreeType structs are represented in MoonFreeType as Lua tables, which are described in this
section. 

There is an (almost) one-to-one correspondence between the table fields and the fields
of the underlying C structs. Refer to the FreeType documentation for their meanings.

* [[bbox]]
[small]#*bbox* = { +
_xmin_, _ymin_: integer, +
_xmax_, _ymax_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_BBox++[FT_BBox])#

* [[bitmapdata]]
[small]#*bitmapdata* = { +
_rows_, _width_, _pitch_, _left_, _top_: integer, +
_pixel_mode_: <<pixelmode, pixelmode>>, +
_num_grays_: integer (for '_gray_' pixel mode only), +
_buffer_: binary string (#buffer = rows * abs(pitch)), +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Bitmap++[FT_Bitmap])#


* [[bitmapsize]]
[small]#*bitmapsize* = { +
_height_, _width_: integer, +
_size_: integer, +
_x_ppem_, _y_ppem_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Bitmap_Size++[FT_Bitmap_Size])#

* [[charmap]]
[small]#*charmap* = { +
_encoding_: <<encoding, encoding>>, +
_platform_id_, _encoding_id_: integer, +
_platform_name_, _encoding_name_: string (text version of id, may be _nil_), +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_CharMapRec++[FT_CharMapRec])#


* [[glyphdata]]
[small]#*glyphdata* = { +
_metrics_: <<glyphmetrics, glyphmetrics>>, +
_linear_hori_advance_: integer, +
_linear_vert_advance_: integer, +
_advance_: <<matrix, matrix>>, +
_format_: <<glyphformat, glyphformat>>, +
_bitmap_: <<bitmapdata, bitmapdata>> (for '_bitmap_' format  only), +
_outline_: <<outlinedata, outlinedata>> (for '_outline_' and '_plotter_' formats only), +
_subglyphs_: {<<subglyph, subglyph>>} (for '_composite_' format  only), +
_control_data_: binary string (optional), +
_lsb_delta_, _rsb_delta_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_GlyphSlot++[FT_GlyphSlot]) +
Note: The fields _bitmap_left_, and _bitmap_top_ are moved in the <<bitmapdata, bitmapdata>> table (as _bitmap.left_ and _bitmap.top_, respectively).#


* [[glyphmetrics]]
[small]#*glyphmetrics* = { +
_width_, _height_: integer, +
_hori_bearing_x_, _hori_bearing_y_, _hori_advance_: integer, +
_vert_bearing_x_, _vert_bearing_y_, _vert_advance_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Glyph_Metrics++[FT_Glyph_Metrics])#


* [[matrix]]
[small]#*matrix* = { +
_xx_, _xy_: integer, +
_yx_, _yy_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Matrix++[FT_Matrix])#


* [[outlinedata]]
[small]#*outlinedata* = { +
_points_: {<<vector, vector>>}, +
_tags_: {integer} (#tags = #points), +
_type_: {<<pointtype, pointtype>>} (#type = #points), +
_scanmode_: {<<scanmode, scanmode>>} (#scanmode = #points), +
_contours_: {integer} (indices in points array, 1-based), +
_flags_: <<outlineflags, outlineflags>> (integer code), +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html#FT_Outline++[FT_Outline])#

* [[sizemetrics]]
[small]#*sizemetrics* = { +
_x_ppem_, _y_ppem_: integer, +
_y_scale_, _y_scale_: integer, +
_ascender_, _descender_: integer, +
_height_: integer, +
_max_advance_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Size_Metrics++[FT_Size_Metrics])#

* [[subglyph]]
[small]#*subglyph* = { +
_index_: integer (glyph index, 1-based), +
_flags_: <<subglyphflags, subglyphflags>> (integer code), +
_arg1_, _arg2_: integer, +
_transform_: <<matrix, matrix>>, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Get_SubGlyph_Info++[FT_Get_SubGlyph_Info])#

* [[vector]]
[small]#*vector* = { +
_x_, _y_: integer, +
} (rfr: link:++https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Vector++[FT_Vector])#

